# Generated by Django 4.1.2 on 2022-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
